In [2]:
import pandas as pd
import numpy as np

In [11]:
#DataFrame(matrix,index as rows,colums)
df=pd.DataFrame(np.arange(0,50,step=2).reshape(5,5),index=['R1','R2','R3','R4','R5'],columns=['a','b','c','d','e'])
df.head()

a   b   c   d   e
R1   0   2   4   6   8
R2  10  12  14  16  18
R3  20  22  24  26  28
R4  30  32  34  36  38
R5  40  42  44  46  48

In [12]:
#to check particular values
df<20

a      b      c      d      e
R1   True   True   True   True   True
R2   True   True   True   True   True
R3  False  False  False  False  False
R4  False  False  False  False  False
R5  False  False  False  False  False

In [5]:
# matrix to csv file
df.to_csv('Test1.csv')

In [4]:
# Acessing elements

# 1st method - .loc for ROWS
df.loc['R2']

a    5
b    6
c    7
d    8
e    9
Name: R2, dtype: int32

In [5]:
# 2nd method - .iloc for rows and colums
df.iloc[0:2,:]

a  b  c  d  e
R1  0  1  2  3  4
R2  5  6  7  8  9

In [6]:
# 3rd method - to get any colum
df[['a','b']]

a   b
R1   0   1
R2   5   6
R3  10  11
R4  15  16
R5  20  21

In [8]:
#dataframes to array
df.iloc[1:3,:].values

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
#counts nbumber of time each element repeated
df['a'].value_counts()

15    1
5     1
20    1
10    1
0     1
Name: a, dtype: int64

In [10]:
#to get unique values
df['a'].unique()

array([ 0,  5, 10, 15, 20], dtype=int64)

In [14]:
#to generate matrix with 1
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
#to generate random number under any max value
np.random.randint(10)

8

In [19]:
#to generate random matrix with value <1
np.random.rand(2,4)

array([[0.35052667, 0.77903017, 0.51920712, 0.50656981],
       [0.82696375, 0.69194722, 0.80545847, 0.73071128]])

In [27]:
n=np.random.randn(5,4)
n

array([[-0.36488945, -0.80820154, -0.26731055,  1.45631679],
       [ 0.13475602,  0.40375908, -0.50447356, -2.04927584],
       [ 1.45640746,  0.64169616, -0.97122543, -0.04005099],
       [-0.48157758, -0.09882376,  0.7691923 ,  0.58656894],
       [-0.46782688, -0.20933946, -2.36545471, -0.15447894]])

In [29]:
#to find mean median mode
x=n[0:2,:]
y=n[2:,:]
x_mean=np.mean(x)
y_mean=np.mean(y)
print(x_mean,y_mean)

-0.2499148795263202 -0.11124274032811148
